# Generated by Django 5.0.1 on 2024-08-02 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_event_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='trend',
            field=models.BooleanField(),
        ),
    ]
