# Generated by Django 5.0.1 on 2024-08-02 08:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_event_trend'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event_register',
            name='eventId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.event'),
        ),
    ]
