# Generated by Django 5.0.7 on 2024-08-07 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_event_register_eventid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='trend',
            field=models.PositiveIntegerField(default=0, help_text='1 for event to display in home page'),
        ),
    ]
