# Generated by Django 5.0.7 on 2024-08-07 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_event_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
        migrations.RemoveField(
            model_name='event_register',
            name='eventId',
        ),
        migrations.RemoveField(
            model_name='event_register',
            name='userId',
        ),
        migrations.DeleteModel(
            name='Event',
        ),
        migrations.DeleteModel(
            name='Event_Register',
        ),
    ]
