# Generated by Django 5.0.7 on 2024-08-07 04:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_delete_contact_remove_event_register_eventid_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
                ('sendCopy', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trend', models.PositiveIntegerField(blank=True, default=0, help_text='1 for event to display in home page')),
                ('name', models.CharField(max_length=255)),
                ('place', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('organizer', models.CharField(max_length=255)),
                ('organization', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='eventmanagement/images')),
                ('capacity', models.IntegerField()),
                ('small_description', models.TextField()),
                ('location', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=100)),
                ('guest', models.CharField(max_length=255)),
                ('gmap', models.CharField(max_length=1000)),
                ('organization_details', models.TextField()),
                ('inclusions', models.TextField()),
                ('exclusions', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Event_Register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=100)),
                ('lastName', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('age', models.IntegerField()),
                ('businessName', models.CharField(max_length=100)),
                ('organizationName', models.CharField(max_length=100)),
                ('businessAddress', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('zipcode', models.CharField(max_length=100)),
                ('eventId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.event')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.users')),
            ],
        ),
    ]
