# Generated by Django 5.0.7 on 2024-08-07 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_event_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='image_url',
        ),
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.URLField(),
        ),
    ]
