# Generated by Django 5.1 on 2024-08-12 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_event_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='exclusions',
            field=models.TextField(help_text='Use semi-colon to separate'),
        ),
        migrations.AlterField(
            model_name='event',
            name='inclusions',
            field=models.TextField(help_text='Use semi-colon to separate'),
        ),
    ]
